stages:
  - test
  - lint
  - coverage
#  - deploy

default:
  image: python:3.12-alpine

lint:
  stage: lint
  before_script:
    - pip install pylint
    - pip install -r requirements.txt
  script:
    - pylint $(find . -type f -name "*.py" -not -path "*/venv/*")
  allow_failure: true

coverage:
  stage: coverage
  script:
   - pip install pytest-cov
   - pip install -r requirements.dev.txt
   - pytest --cov=. --cov-report=xml
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

test:
  stage: test
  script:
  - echo "Starting test..."
  - apk add --no-cache gcc python3-dev musl-dev linux-headers make
  - pip install -r requirements.dev.txt
  - apk add --no-cache make
  - make environment
  - make test

# Step below are not useful for the moment

#staging:
#  stage: deploy
#  script:
#  - echo "Deploying application on production environnement [NOT IMPLEMENTED YET]"
#  only:
#  - master

#production:
#  stage: deploy
#  script:
#  - echo "Deploying application on pre-production environnement [NOT IMPLEMENTED YET]"
#  only:
#  - develop

#lint:
#  stage: lint
#  script:
#  - echo "Checking for code quality [NOT IMPLEMENTED YET]"

