---
stages:
  - test
  - lint
  - coverage
default:
  image: python:3.12-alpine

lint:
  stage: lint
  before_script:
    - apk add --no-cache gcc python3-dev musl-dev linux-headers jq
    - pip install pylint
    - pip install -r requirements.txt
  script:
    - pylint src/ --fail-under=7.5
  allow_failure: false
 
 

test:
  stage: test
  script:
    - echo "Starting test..."
    - apk add --no-cache gcc python3-dev musl-dev linux-headers make 
    - pip install -r requirements.dev.txt
    - apk add --no-cache make
    - make environment
    - make test 

  
coverage:
  stage: coverage
  script:
   - apk add --no-cache gcc python3-dev musl-dev linux-headers
   - pip install pytest-cov
   - pip install -r requirements.dev.txt
   - pytest --cov=src --cov-report=xml --cov-report=term-missing --cov-config=.coveragerc --cov-fail-under=82.71
  artifacts:
    paths: 
      - coverage.xml
 