stages:
  - test
  - lint
  - coverage
  - build 
  - deploy


default:
  image: python:3.12-alpine



lint:
  stage: lint
  before_script:
    - apk add --no-cache gcc python3-dev musl-dev linux-headers jq
    - pip install pylint
    - pip install -r requirements.txt
  script:
    - pylint src/ --disable=R0011,W292,C0301 --fail-under=7.5
  allow_failure: false
 
 

test:
  stage: test
  script:
    - echo "Starting test..."
    - apk add --no-cache gcc python3-dev musl-dev linux-headers make 
    - python3 -m ensurepip  # Installe pip si ce n'est pas déjà fait
    - python3 -m pip install --upgrade pip  # Met à jour pip
    - pip install -r requirements.dev.txt
    - apk add --no-cache make
    - make environment
    - make test 

  
coverage:
  stage: coverage
  script:
   - apk add --no-cache gcc python3-dev musl-dev linux-headers
   - pip install pytest-cov
   - pip install -r requirements.dev.txt
   - pytest --cov=src --cov-report=xml --cov-report=term-missing --cov-config=.coveragerc --cov-fail-under=82.71
  artifacts:
    paths: 
      - coverage.xml



image: docker:19.03.12

variables:
  CI_REGISTRY_IMAGE: devops.telecomste.fr:5050/printerfaceadmin/2024-25/group8/ia-groupe-8
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  CI_REGISTRY_USER: TokenDockerAgent 
  CI_REGISTRY_PASSWORD: glpat-RKs7JCFTd8Tr8KsHPcxf

services:
  - name: docker:dind
    entrypoint: ["env", "-u", "DOCKER_HOST"]
    command: ["dockerd-entrypoint.sh"]

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY


build:
  stage: build
  script:
    - DATEPRECISE=$(date +"%Y%m%d-%H%M%S")
    - docker build --pull -t "$CI_REGISTRY_IMAGE:latest" .
    - docker tag "$CI_REGISTRY_IMAGE:latest" "$CI_REGISTRY_IMAGE:$TDATEPRECISE"
    - docker push "$CI_REGISTRY_IMAGE:latest"
    - docker push "$CI_REGISTRY_IMAGE:$DATEPRECISE"


deploy:
  stage: deploy
  script:
    - docker pull "$CI_REGISTRY_IMAGE:main"''
    - docker run -d --name latest -p 8080:8080 "$CI_REGISTRY_IMAGE:main"
  only:
    - main
 