---
stages:
  - test
  - lint
  - coverage
default:
  image: python:3.12-alpine

lint:
  stage: lint
  before_script:
    - apk add --no-cache gcc python3-dev musl-dev linux-headers jq
    - pip install -r requirements.dev.txt
  script:
    - pylint src/ --disable=R0011,W292,C0301 --fail-under=7.6
  allow_failure: false
 
 

test:
  stage: test
  script:
    - echo "Starting test..."
    - apk add --no-cache gcc python3-dev musl-dev linux-headers make 
    - pip install -r requirements.dev.txt
    - pip install -r requirements.txt
    - apk add --no-cache make
    - make environment
    - make test 


coverage:
  stage: coverage
  script:
   - apk add --no-cache gcc python3-dev musl-dev linux-headers
   - pip install -r requirements.dev.txt
   - pip install -r requirements.txt
   - pytest --cov=src --cov-report=xml --cov-report=term-missing --cov-config=.coveragerc --cov-fail-under=82.71
  coverage: /TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/
  artifacts:
    
    paths:
      - coverage.xml
  

  