stages:
 - test
 - lint
 - coverage
# - deploy

default:
  image: python:3.12-alpine

lint:
  stage: lint
  before_script:
   - pip install pylint
   - pip install -r requirements.txt
  script:
   - pylint $(find . -type f -name "*.py" -not -path "*/venv/*")
  allow_failure: true

test:
  stage: test
  script:
   - echo "Starting test..."
   - apk add --no-cache gcc python3-dev musl-dev linux-headers make
   - pip install -r requirements.dev.txt
   - apk add --no-cache make
   - make environment
   - make test

coverage:
  stage: coverage
  script:
   - apk add --no-cache gcc python3-dev musl-dev linux-headers
   - pip install pytest-cov
   - pip install -r requirements.dev.txt
   - pytest --cov=src --cov-report=xml --cov-report=term-missing --cov-config=.coveragerc --cov-fail-under=82.71
  artifacts:
    paths: 
      - coverage.xml